"""Agregar_tabla_de_auditoria

Revision ID: b530f62f41f4
Revises: 0d2a8c43ec03
Create Date: 2026-02-27 19:51:54.682459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b530f62f41f4'
down_revision: Union[str, None] = '0d2a8c43ec03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###